repos:
  - repo: https://github.com/nix-community/alejandra
    rev: "4.0.0"
    hooks:
      - id: alejandra
        always_run: true
        exclude: ^(.*/)?(flake\.lock|result.*|\.direnv|.devenv|.git)$

  - repo: https://github.com/astro/misc-nix
    rev: "v0.0.1"
    hooks:
      - id: statix
        always_run: true
        exclude: ^(.*/)?(flake\.lock|result.*|\.direnv|.devenv|.git)$

  - repo: https://github.com/astro/deadnix
    rev: "v3.1.0"
    hooks:
      - id: deadnix
        always_run: true
        exclude: ^(.*/)?(flake\.lock|result.*|\.direnv|.devenv|.git)$
